version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: raw
        identifier: raw_gz_product
      - name: raw
        identifier: raw_gz_sales
      - name: raw
        identifier: raw_gz_ship
